tema = "BlueMono"
logo = "./imagens/logo.png"
logo2 = "./imagens/logo2.png"
fonte_texto = ("tahoma", 10)
tamanho_texto= (20, 1)
fonte_titulo = ("tahoma", 12)
tamanho_janela = (450, 480)
tamanho_aviso = (200, 100)
tamanho_fonte_aviso = (20, 2)
fundo_listas = "white"
cor_titulo = "white"
fundo_titulo = "#8360C3"
tamanho_texto_mostra_dados = (50,1)
tamanho_texto_pega_dados_tarefa = (25,1)